# Default values for url-shortener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: "url-shortener"
labels: "url-shortener"
replicaCount: 1
appEnv: "prod"

image:
  repository: vumanskyi/url-shortener
  tag: "1.0"
  pullPolicy: IfNotPresent

appPort: 8080

redis:
  image:
    repository: redis
    tag: "7.4-alpine"
  host: redis
  port: 6379
  password: ""
  db: "0"

service:
  type: NodePort
  port: 8080

redisService:
  type: NodePort
  port: 6379

ingress:
  enabled: false
