apiVersion: apps/v1
kind: Deployment
metadata:
    name: url-shortener
    labels:
        app: url-shortener
spec:
    replicas: 1
    selector:
        matchLabels:
            app: url-shortener
    template:
        metadata:
            labels:
                app: url-shortener
        spec:
            containers:
                - name: url-shortener
                  image: vumanskyi/url-shortener:1.0
                  ports:
                      - containerPort: 8080
                  env:
                    - name: APP_ENV
                      value: "prod"
                    - name: APP_PORT
                      value: "8080"
                    - name: REDIS_HOST
                      value: "redis"
                    - name: REDIS_PORT
                      value: "6379"
                    - name: REDIS_PASSWORD
                      value: ""
                    - name: REDIS_DB
                      value: "0"