apiVersion: v1
kind: Service
metadata:
    name: app
    labels:
        app: app
spec:
    type: NodePort
    selector:
        app: app
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
