apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: {{ .Values.redisService.type }}
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redisService.port }}
      targetPort: {{ .Values.redis.port }}
